apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sgwqdxfyn-go 
  janus-idp.io/tekton: sgwqdxfyn-go
  backstage.io/kubernetes-id: sgwqdxfyn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sgwqdxfyn-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml